language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PINS="git.dev:. git-http.dev:. git-unix.dev:. git-mirage.dev:."
  matrix:
    - OCAML_VERSION=4.07 PACKAGE="git.dev"
    - OCAML_VERSION=4.08.1 PACKAGE="git.dev"
    - OCAML_VERSION=4.07 PACKAGE="git-unix.dev"
    - OCAML_VERSION=4.07 PACKAGE="git-unix.dev"
    - OCAML_VERSION=4.07 PACKAGE="git-mirage.dev"
    - OCAML_VERSION=4.07 PACKAGE="git.dev" REVDEPS=*
